### ISSUE TITLE
I dont know how to create dynamic routes on remix shopify app template

### ISSUE THREAD

**Issue by juddydev** [juddydev/r3f-3D-viewer#26]
I created remix route like this
 > products/$handle
products/$handle/custom

in products/$handle.route, I created a link
---<Link to={`products/${handle}/custom`} />

The link url changed, but the custom page doesnt load

**Comment by maxmos001** [comment]
You should change the path name like this

 > products.$handle._index
products.$handle.custom

**Comment by juddydev** [comment]
Wow, it's works well
Thank you

**Comment by maxmos001** [comment]
You can also study this tutorial
https://remix.run/docs/en/main/file-conventions/routes#nested-routes
